import type { Locale } from "@/lib/i18n";
type SettingsCopy={center:string;title:string;intro:string;security:string;change:string;active:string;admin:string;member:string;dark:string;themeHint:string;team:string;teamHint:string;openUsers:string;current:string;newPassword:string;confirm:string;passwordHint:string;updating:string;changeButton:string;failed:string;success:string;connection:string};
export const settingsCopy:Record<Locale,SettingsCopy>={
en:{center:"Account center",title:"Settings",intro:"Manage your account, appearance and workspace security.",security:"Security",change:"Change password",active:"Active account",admin:"Administrator account",member:"Workspace member",dark:"Dark appearance",themeHint:"The theme control stores your preference on this device.",team:"Team management",teamHint:"Invite users, update roles and revoke access.",openUsers:"Open users",current:"Current password",newPassword:"New password",confirm:"Confirm new password",passwordHint:"Use at least 12 characters. Previous session tokens become invalid after the change.",updating:"Updating…",changeButton:"Change password",failed:"Password could not be changed.",success:"Password changed; other active sessions were closed.",connection:"Could not connect. Please try again."},
tr:{center:"Hesap merkezi",title:"Ayarlar",intro:"Hesabını, görünümü ve çalışma alanı güvenliğini yönet.",security:"Güvenlik",change:"Parola değiştir",active:"Aktif hesap",admin:"Yönetici hesabı",member:"Çalışma alanı üyesi",dark:"Koyu görünüm",themeHint:"Tema tercihin bu cihazda saklanır.",team:"Ekip yönetimi",teamHint:"Kullanıcı davet et, rolleri güncelle ve erişimi kaldır.",openUsers:"Kullanıcıları aç",current:"Mevcut parola",newPassword:"Yeni parola",confirm:"Yeni parola tekrar",passwordHint:"En az 12 karakter kullan. Değişiklikten sonra eski oturum belirteçleri geçersiz olur.",updating:"Güncelleniyor…",changeButton:"Parolayı değiştir",failed:"Parola değiştirilemedi.",success:"Parola değiştirildi; diğer aktif oturumlar kapatıldı.",connection:"Bağlantı kurulamadı. Lütfen tekrar dene."},
es:{center:"Centro de cuenta",title:"Ajustes",intro:"Gestiona tu cuenta, apariencia y seguridad del espacio.",security:"Seguridad",change:"Cambiar contraseña",active:"Cuenta activa",admin:"Cuenta administradora",member:"Miembro del espacio",dark:"Apariencia oscura",themeHint:"La preferencia de tema se guarda en este dispositivo.",team:"Gestión del equipo",teamHint:"Invita usuarios, actualiza roles y revoca accesos.",openUsers:"Abrir usuarios",current:"Contraseña actual",newPassword:"Nueva contraseña",confirm:"Confirmar nueva contraseña",passwordHint:"Usa al menos 12 caracteres. Las sesiones anteriores se invalidan después del cambio.",updating:"Actualizando…",changeButton:"Cambiar contraseña",failed:"No se pudo cambiar la contraseña.",success:"Contraseña cambiada; se cerraron las otras sesiones.",connection:"No se pudo conectar. Inténtalo de nuevo."},
de:{center:"Kontocenter",title:"Einstellungen",intro:"Konto, Darstellung und Sicherheit des Arbeitsbereichs verwalten.",security:"Sicherheit",change:"Passwort ändern",active:"Aktives Konto",admin:"Administratorkonto",member:"Mitglied",dark:"Dunkle Darstellung",themeHint:"Die Theme-Auswahl wird auf diesem Gerät gespeichert.",team:"Teamverwaltung",teamHint:"Benutzer einladen, Rollen ändern und Zugriff entziehen.",openUsers:"Benutzer öffnen",current:"Aktuelles Passwort",newPassword:"Neues Passwort",confirm:"Neues Passwort bestätigen",passwordHint:"Mindestens 12 Zeichen verwenden. Frühere Sitzungen werden nach der Änderung ungültig.",updating:"Aktualisieren…",changeButton:"Passwort ändern",failed:"Passwort konnte nicht geändert werden.",success:"Passwort geändert; andere Sitzungen wurden geschlossen.",connection:"Verbindung fehlgeschlagen. Bitte erneut versuchen."},
no:{center:"Kontosenter",title:"Innstillinger",intro:"Administrer konto, utseende og sikkerhet.",security:"Sikkerhet",change:"Endre passord",active:"Aktiv konto",admin:"Administratorkonto",member:"Medlem",dark:"Mørkt utseende",themeHint:"Temavalget lagres på denne enheten.",team:"Teamadministrasjon",teamHint:"Inviter brukere, oppdater roller og fjern tilgang.",openUsers:"Åpne brukere",current:"Nåværende passord",newPassword:"Nytt passord",confirm:"Bekreft nytt passord",passwordHint:"Bruk minst 12 tegn. Tidligere økter blir ugyldige etter endringen.",updating:"Oppdaterer…",changeButton:"Endre passord",failed:"Passordet kunne ikke endres.",success:"Passordet ble endret; andre økter ble lukket.",connection:"Kunne ikke koble til. Prøv igjen."},
ja:{center:"アカウントセンター",title:"設定",intro:"アカウント、表示、ワークスペースのセキュリティを管理します。",security:"セキュリティ",change:"パスワードを変更",active:"使用中のアカウント",admin:"管理者アカウント",member:"ワークスペースメンバー",dark:"ダーク表示",themeHint:"テーマ設定はこの端末に保存されます。",team:"チーム管理",teamHint:"ユーザーの招待、役割の更新、アクセスの無効化を行います。",openUsers:"ユーザーを開く",current:"現在のパスワード",newPassword:"新しいパスワード",confirm:"新しいパスワードを確認",passwordHint:"12文字以上を使用してください。変更後、以前のセッションは無効になります。",updating:"更新中…",changeButton:"パスワードを変更",failed:"パスワードを変更できませんでした。",success:"パスワードを変更し、他のセッションを終了しました。",connection:"接続できませんでした。もう一度お試しください。"},
ko:{center:"계정 센터",title:"설정",intro:"계정, 화면 및 작업 공간 보안을 관리하세요.",security:"보안",change:"비밀번호 변경",active:"활성 계정",admin:"관리자 계정",member:"작업 공간 멤버",dark:"다크 화면",themeHint:"테마 설정은 이 기기에 저장됩니다.",team:"팀 관리",teamHint:"사용자를 초대하고 역할을 변경하거나 접근을 해제하세요.",openUsers:"사용자 열기",current:"현재 비밀번호",newPassword:"새 비밀번호",confirm:"새 비밀번호 확인",passwordHint:"12자 이상 사용하세요. 변경 후 이전 세션은 무효화됩니다.",updating:"업데이트 중…",changeButton:"비밀번호 변경",failed:"비밀번호를 변경하지 못했습니다.",success:"비밀번호가 변경되었고 다른 세션이 종료되었습니다.",connection:"연결할 수 없습니다. 다시 시도하세요."}
};
