import type { Locale } from "@/lib/i18n";
type CuppingCopy={title:string;intro:string;new:string;coffee:string;session:string;score:string;notes:string;noNotes:string;empty:string;emptyHint:string;first:string;back:string;newTitle:string;newIntro:string;addFirst:string;addFirstHint:string;addCoffee:string;choose:string;structured:string;sensoryNotes:string;placeholder:string;personalNotice:string;saving:string;save:string;chooseError:string;saveError:string;dimensions:[string,string][]};
const dims={
en:[["Fragrance / aroma","Dry fragrance and wet aroma"],["Flavor","Quality, intensity and character"],["Aftertaste","Length and quality of the finish"],["Acidity","Brightness, structure and quality"],["Sweetness","Perceived sweetness and ripeness"],["Body","Weight and tactile quality"],["Balance","How the attributes work together"],["Overall","Your holistic impression"]],
tr:[["Koku / aroma","Kuru koku ve ıslak aroma"],["Lezzet","Kalite, yoğunluk ve karakter"],["Bitiş","Bitişin uzunluğu ve kalitesi"],["Asidite","Canlılık, yapı ve kalite"],["Tatlılık","Algılanan tatlılık ve olgunluk"],["Gövde","Ağırlık ve dokunsal kalite"],["Denge","Niteliklerin birlikte çalışması"],["Genel","Bütünsel izlenimin"]],
es:[["Fragancia / aroma","Fragancia seca y aroma húmedo"],["Sabor","Calidad, intensidad y carácter"],["Retrogusto","Duración y calidad del final"],["Acidez","Brillo, estructura y calidad"],["Dulzor","Dulzor y madurez percibidos"],["Cuerpo","Peso y calidad táctil"],["Equilibrio","Cómo funcionan juntos los atributos"],["General","Tu impresión global"]],
de:[["Duft / Aroma","Trockenduft und nasses Aroma"],["Geschmack","Qualität, Intensität und Charakter"],["Nachgeschmack","Länge und Qualität des Abgangs"],["Säure","Lebendigkeit, Struktur und Qualität"],["Süße","Wahrgenommene Süße und Reife"],["Körper","Gewicht und taktile Qualität"],["Balance","Zusammenspiel der Eigenschaften"],["Gesamt","Dein ganzheitlicher Eindruck"]],
no:[["Duft / aroma","Tørr duft og våt aroma"],["Smak","Kvalitet, intensitet og karakter"],["Ettersmak","Lengde og kvalitet på avslutningen"],["Syrlighet","Friskhet, struktur og kvalitet"],["Sødme","Opplevd sødme og modenhet"],["Kropp","Vekt og taktil kvalitet"],["Balanse","Hvordan egenskapene virker sammen"],["Helhet","Ditt helhetsinntrykk"]],
ja:[["香り / アロマ","乾いた粉と抽出時の香り"],["風味","品質、強さ、特徴"],["後味","余韻の長さと品質"],["酸味","明るさ、構造、品質"],["甘さ","感じられる甘さと熟度"],["質感","重さと触感の品質"],["バランス","各特性の調和"],["総合","全体的な印象"]],
ko:[["향 / 아로마","마른 향과 젖은 향"],["풍미","품질, 강도, 특성"],["여운","마무리의 길이와 품질"],["산미","선명도, 구조, 품질"],["단맛","느껴지는 단맛과 숙도"],["바디","무게감과 촉감 품질"],["균형","특성들이 어우러지는 정도"],["종합","전체적인 인상"]]
} satisfies Record<Locale,[string,string][]>;
export const cuppingCopy:Record<Locale,CuppingCopy>={
en:{title:"Cupping",intro:"Structured sensory sessions linked to the coffees in your library.",new:"New cupping",coffee:"Coffee",session:"Session",score:"Score",notes:"Notes",noNotes:"No notes",empty:"No cupping sessions yet",emptyHint:"Start with an active coffee and record what you taste.",first:"Create first cupping",back:"Cupping sessions",newTitle:"New cupping",newIntro:"Evaluate one coffee across eight sensory dimensions. This is a structured personal score, not an official SCA protocol.",addFirst:"Add a coffee first",addFirstHint:"A cupping session must be linked to a coffee in your library.",addCoffee:"Add coffee",choose:"Choose an active coffee",structured:"Structured score",sensoryNotes:"Sensory notes",placeholder:"Fragrance, flavor development, finish, defects and observations…",personalNotice:"Scores are saved as a structured personal evaluation, not an official SCA score.",saving:"Saving…",save:"Save cupping",chooseError:"Choose a coffee before saving the cupping.",saveError:"Cupping could not be saved.",dimensions:dims.en},
tr:{title:"Cupping",intro:"Kütüphanendeki çekirdeklere bağlı yapılandırılmış duyusal oturumlar.",new:"Yeni cupping",coffee:"Çekirdek",session:"Oturum",score:"Puan",notes:"Notlar",noNotes:"Not yok",empty:"Henüz cupping oturumu yok",emptyHint:"Aktif bir çekirdekle başla ve aldığın tatları kaydet.",first:"İlk cupping kaydını oluştur",back:"Cupping oturumları",newTitle:"Yeni cupping",newIntro:"Bir çekirdeği sekiz duyusal boyutta değerlendir. Bu kişisel ve yapılandırılmış bir puandır; resmî SCA protokolü değildir.",addFirst:"Önce çekirdek ekle",addFirstHint:"Cupping oturumu kütüphanendeki bir çekirdeğe bağlı olmalıdır.",addCoffee:"Çekirdek ekle",choose:"Aktif çekirdek seç",structured:"Yapılandırılmış puan",sensoryNotes:"Duyusal notlar",placeholder:"Koku, lezzet gelişimi, bitiş, kusurlar ve gözlemler…",personalNotice:"Puanlar resmî SCA skoru olarak değil, yapılandırılmış kişisel değerlendirme olarak kaydedilir.",saving:"Kaydediliyor…",save:"Cupping kaydet",chooseError:"Kaydetmeden önce bir çekirdek seç.",saveError:"Cupping kaydedilemedi.",dimensions:dims.tr},
es:{title:"Cata",intro:"Sesiones sensoriales estructuradas vinculadas a los cafés de tu biblioteca.",new:"Nueva cata",coffee:"Café",session:"Sesión",score:"Puntuación",notes:"Notas",noNotes:"Sin notas",empty:"Aún no hay catas",emptyHint:"Empieza con un café activo y registra lo que percibes.",first:"Crear primera cata",back:"Sesiones de cata",newTitle:"Nueva cata",newIntro:"Evalúa un café en ocho dimensiones sensoriales. Es una puntuación personal estructurada, no un protocolo SCA oficial.",addFirst:"Primero añade un café",addFirstHint:"La cata debe estar vinculada a un café de tu biblioteca.",addCoffee:"Añadir café",choose:"Elige un café activo",structured:"Puntuación estructurada",sensoryNotes:"Notas sensoriales",placeholder:"Fragancia, evolución del sabor, final, defectos y observaciones…",personalNotice:"Se guarda como evaluación personal estructurada, no como puntuación SCA oficial.",saving:"Guardando…",save:"Guardar cata",chooseError:"Elige un café antes de guardar la cata.",saveError:"No se pudo guardar la cata.",dimensions:dims.es},
de:{title:"Cupping",intro:"Strukturierte sensorische Sitzungen zu den Kaffees deiner Sammlung.",new:"Neues Cupping",coffee:"Kaffee",session:"Sitzung",score:"Wertung",notes:"Notizen",noNotes:"Keine Notizen",empty:"Noch keine Cuppings",emptyHint:"Mit einem aktiven Kaffee beginnen und Eindrücke festhalten.",first:"Erstes Cupping erstellen",back:"Cupping-Sitzungen",newTitle:"Neues Cupping",newIntro:"Einen Kaffee in acht sensorischen Dimensionen bewerten. Dies ist eine strukturierte persönliche Wertung, kein offizielles SCA-Protokoll.",addFirst:"Zuerst Kaffee hinzufügen",addFirstHint:"Ein Cupping muss mit einem Kaffee deiner Sammlung verknüpft sein.",addCoffee:"Kaffee hinzufügen",choose:"Aktiven Kaffee wählen",structured:"Strukturierte Wertung",sensoryNotes:"Sensorische Notizen",placeholder:"Duft, Geschmacksentwicklung, Abgang, Fehler und Beobachtungen…",personalNotice:"Die Wertung wird als persönliche Bewertung gespeichert, nicht als offizieller SCA-Score.",saving:"Speichern…",save:"Cupping speichern",chooseError:"Vor dem Speichern einen Kaffee wählen.",saveError:"Cupping konnte nicht gespeichert werden.",dimensions:dims.de},
no:{title:"Cupping",intro:"Strukturerte sensoriske økter knyttet til kaffen i biblioteket ditt.",new:"Ny cupping",coffee:"Kaffe",session:"Økt",score:"Poeng",notes:"Notater",noNotes:"Ingen notater",empty:"Ingen cuppingøkter ennå",emptyHint:"Start med en aktiv kaffe og registrer det du smaker.",first:"Opprett første cupping",back:"Cuppingøkter",newTitle:"Ny cupping",newIntro:"Vurder én kaffe på åtte sensoriske dimensjoner. Dette er en strukturert personlig poengsum, ikke en offisiell SCA-protokoll.",addFirst:"Legg til kaffe først",addFirstHint:"En cuppingøkt må knyttes til en kaffe i biblioteket.",addCoffee:"Legg til kaffe",choose:"Velg en aktiv kaffe",structured:"Strukturert poeng",sensoryNotes:"Sensoriske notater",placeholder:"Duft, smaksutvikling, avslutning, feil og observasjoner…",personalNotice:"Poeng lagres som personlig vurdering, ikke som offisiell SCA-poengsum.",saving:"Lagrer…",save:"Lagre cupping",chooseError:"Velg kaffe før du lagrer cuppingen.",saveError:"Cuppingen kunne ikke lagres.",dimensions:dims.no},
ja:{title:"カッピング",intro:"ライブラリのコーヒーに紐づく構造化された官能評価です。",new:"新規カッピング",coffee:"コーヒー",session:"セッション",score:"スコア",notes:"メモ",noNotes:"メモなし",empty:"カッピング記録はまだありません",emptyHint:"使用中のコーヒーを選び、感じた味を記録しましょう。",first:"最初のカッピングを作成",back:"カッピング記録",newTitle:"新規カッピング",newIntro:"一つのコーヒーを八つの官能項目で評価します。これは個人用の構造化スコアで、公式SCAプロトコルではありません。",addFirst:"先にコーヒーを追加",addFirstHint:"カッピングはライブラリ内のコーヒーに紐づける必要があります。",addCoffee:"コーヒーを追加",choose:"使用中のコーヒーを選択",structured:"構造化スコア",sensoryNotes:"官能メモ",placeholder:"香り、風味の変化、後味、欠点、観察事項…",personalNotice:"公式SCAスコアではなく、個人用の構造化評価として保存されます。",saving:"保存中…",save:"カッピングを保存",chooseError:"保存する前にコーヒーを選択してください。",saveError:"カッピングを保存できませんでした。",dimensions:dims.ja},
ko:{title:"커핑",intro:"라이브러리의 원두와 연결된 구조화된 관능 평가입니다.",new:"새 커핑",coffee:"원두",session:"세션",score:"점수",notes:"메모",noNotes:"메모 없음",empty:"아직 커핑 기록이 없습니다",emptyHint:"활성 원두를 선택하고 느낀 맛을 기록하세요.",first:"첫 커핑 만들기",back:"커핑 세션",newTitle:"새 커핑",newIntro:"원두 하나를 여덟 가지 관능 항목으로 평가합니다. 개인용 구조화 점수이며 공식 SCA 프로토콜이 아닙니다.",addFirst:"먼저 원두 추가",addFirstHint:"커핑 세션은 라이브러리의 원두와 연결되어야 합니다.",addCoffee:"원두 추가",choose:"활성 원두 선택",structured:"구조화 점수",sensoryNotes:"관능 메모",placeholder:"향, 풍미 전개, 여운, 결점 및 관찰…",personalNotice:"공식 SCA 점수가 아닌 개인용 구조화 평가로 저장됩니다.",saving:"저장 중…",save:"커핑 저장",chooseError:"저장하기 전에 원두를 선택하세요.",saveError:"커핑을 저장하지 못했습니다.",dimensions:dims.ko}
};
