import type { Locale } from "@/lib/i18n";

type BeanCopy = {
  back: string; kicker: string; title: string; intro: string; identity: string; labelQuestion: string;
  roaster: string; name: string; origin: string; variety: string; optional: string; process: string;
  freshness: string; timeline: string; roastDate: string; openDate: string; archived: string;
  checkFields: string; saveFailed: string; connectionFailed: string; followLater: string; saving: string; save: string;
  roasterExample: string; nameExample: string; originExample: string; varietyExample: string; processExample: string;
};

export const beanCopy: Record<Locale, BeanCopy> = {
  en: { back:"Beans", kicker:"New package", title:"Add coffee to your library", intro:"Record the package details. The roast date powers freshness guidance.", identity:"Identity", labelQuestion:"What does the label say?", roaster:"Roaster", name:"Coffee name", origin:"Origin", variety:"Variety", optional:"optional", process:"Process", freshness:"Freshness", timeline:"Package timeline", roastDate:"Roast date", openDate:"Opened date", archived:"Start package as archived", checkFields:"Check the highlighted fields.", saveFailed:"Coffee could not be saved.", connectionFailed:"Could not connect. Please try again.", followLater:"You can track these details later from the package page.", saving:"Saving…", save:"Save coffee", roasterExample:"e.g. Null Coffee", nameExample:"e.g. Finca El Paraiso", originExample:"e.g. Colombia", varietyExample:"e.g. Red Bourbon", processExample:"e.g. Washed, Natural, Anaerobic" },
  tr: { back:"Çekirdekler", kicker:"Yeni paket", title:"Kütüphanene çekirdek ekle", intro:"Paket bilgilerini kaydet. Kavrum tarihi tazelik yönlendirmesini oluşturur.", identity:"Kimlik", labelQuestion:"Etikette ne yazıyor?", roaster:"Kavurucu", name:"Çekirdek adı", origin:"Menşei", variety:"Varyete", optional:"opsiyonel", process:"İşlem", freshness:"Tazelik", timeline:"Paketin zaman çizgisi", roastDate:"Kavrum tarihi", openDate:"Paket açılışı", archived:"Paketi arşivde başlat", checkFields:"İşaretli alanları kontrol et.", saveFailed:"Çekirdek kaydedilemedi.", connectionFailed:"Bağlantı kurulamadı. Lütfen yeniden dene.", followLater:"Bilgileri daha sonra paket detayından izleyebilirsin.", saving:"Kaydediliyor…", save:"Çekirdeği kaydet", roasterExample:"Örn. Null Coffee", nameExample:"Örn. Finca El Paraiso", originExample:"Örn. Colombia", varietyExample:"Örn. Red Bourbon", processExample:"Örn. Washed, Natural, Anaerobic" },
  es: { back:"Cafés", kicker:"Nuevo paquete", title:"Añade café a tu biblioteca", intro:"Registra los datos del paquete. La fecha de tueste orienta la frescura.", identity:"Identidad", labelQuestion:"¿Qué dice la etiqueta?", roaster:"Tostador", name:"Nombre del café", origin:"Origen", variety:"Variedad", optional:"opcional", process:"Proceso", freshness:"Frescura", timeline:"Cronología del paquete", roastDate:"Fecha de tueste", openDate:"Fecha de apertura", archived:"Iniciar el paquete como archivado", checkFields:"Revisa los campos marcados.", saveFailed:"No se pudo guardar el café.", connectionFailed:"No se pudo conectar. Inténtalo de nuevo.", followLater:"Puedes consultar estos datos después en la página del paquete.", saving:"Guardando…", save:"Guardar café", roasterExample:"p. ej. Null Coffee", nameExample:"p. ej. Finca El Paraiso", originExample:"p. ej. Colombia", varietyExample:"p. ej. Red Bourbon", processExample:"p. ej. Lavado, Natural, Anaeróbico" },
  de: { back:"Bohnen", kicker:"Neue Packung", title:"Kaffee zur Sammlung hinzufügen", intro:"Packungsdaten erfassen. Das Röstdatum steuert die Frischehinweise.", identity:"Identität", labelQuestion:"Was steht auf dem Etikett?", roaster:"Rösterei", name:"Kaffeename", origin:"Herkunft", variety:"Varietät", optional:"optional", process:"Aufbereitung", freshness:"Frische", timeline:"Zeitachse der Packung", roastDate:"Röstdatum", openDate:"Öffnungsdatum", archived:"Packung archiviert anlegen", checkFields:"Markierte Felder prüfen.", saveFailed:"Kaffee konnte nicht gespeichert werden.", connectionFailed:"Verbindung fehlgeschlagen. Bitte erneut versuchen.", followLater:"Diese Angaben lassen sich später auf der Packungsseite verfolgen.", saving:"Speichern…", save:"Kaffee speichern", roasterExample:"z. B. Null Coffee", nameExample:"z. B. Finca El Paraiso", originExample:"z. B. Colombia", varietyExample:"z. B. Red Bourbon", processExample:"z. B. Washed, Natural, Anaerobic" },
  no: { back:"Bønner", kicker:"Ny pose", title:"Legg kaffe til i biblioteket", intro:"Registrer posedetaljene. Brennedatoen brukes til ferskhetsveiledning.", identity:"Identitet", labelQuestion:"Hva står på etiketten?", roaster:"Brenneri", name:"Kaffenavn", origin:"Opprinnelse", variety:"Varietet", optional:"valgfritt", process:"Prosess", freshness:"Ferskhet", timeline:"Posens tidslinje", roastDate:"Brennedato", openDate:"Åpningsdato", archived:"Start posen som arkivert", checkFields:"Kontroller de markerte feltene.", saveFailed:"Kaffen kunne ikke lagres.", connectionFailed:"Kunne ikke koble til. Prøv igjen.", followLater:"Du kan følge disse detaljene senere fra posesiden.", saving:"Lagrer…", save:"Lagre kaffe", roasterExample:"f.eks. Null Coffee", nameExample:"f.eks. Finca El Paraiso", originExample:"f.eks. Colombia", varietyExample:"f.eks. Red Bourbon", processExample:"f.eks. Vasket, Natural, Anaerob" },
  ja: { back:"豆", kicker:"新しいパッケージ", title:"コーヒーをライブラリに追加", intro:"パッケージ情報を記録します。焙煎日を基に鮮度を案内します。", identity:"基本情報", labelQuestion:"ラベルの内容", roaster:"ロースター", name:"コーヒー名", origin:"産地", variety:"品種", optional:"任意", process:"精製方法", freshness:"鮮度", timeline:"パッケージの履歴", roastDate:"焙煎日", openDate:"開封日", archived:"アーカイブ済みとして開始", checkFields:"強調表示された項目を確認してください。", saveFailed:"コーヒーを保存できませんでした。", connectionFailed:"接続できませんでした。もう一度お試しください。", followLater:"これらの情報は後でパッケージページから確認できます。", saving:"保存中…", save:"コーヒーを保存", roasterExample:"例：Null Coffee", nameExample:"例：Finca El Paraiso", originExample:"例：Colombia", varietyExample:"例：Red Bourbon", processExample:"例：Washed、Natural、Anaerobic" },
  ko: { back:"원두", kicker:"새 패키지", title:"라이브러리에 원두 추가", intro:"패키지 정보를 기록하세요. 로스팅 날짜를 기준으로 신선도를 안내합니다.", identity:"기본 정보", labelQuestion:"라벨에 무엇이 적혀 있나요?", roaster:"로스터", name:"원두 이름", origin:"원산지", variety:"품종", optional:"선택", process:"가공 방식", freshness:"신선도", timeline:"패키지 타임라인", roastDate:"로스팅 날짜", openDate:"개봉 날짜", archived:"보관 완료 상태로 시작", checkFields:"강조된 항목을 확인하세요.", saveFailed:"원두를 저장하지 못했습니다.", connectionFailed:"연결할 수 없습니다. 다시 시도하세요.", followLater:"이 정보는 나중에 패키지 페이지에서 확인할 수 있습니다.", saving:"저장 중…", save:"원두 저장", roasterExample:"예: Null Coffee", nameExample:"예: Finca El Paraiso", originExample:"예: Colombia", varietyExample:"예: Red Bourbon", processExample:"예: Washed, Natural, Anaerobic" }
};
