import type { Locale } from "@/lib/i18n";

type BrewListCopy = { kicker:string; title:string; intro:string; record:string; summary:string; total:string; average:string; highest:string; method:string; allMethods:string; minScore:string; allScores:string; andAbove:string; apply:string; clear:string; records:string; page:string; empty:string; emptyHint:string; ratio:string; temperature:string; duration:string; bean:string; recipe:string; score:string; date:string; action:string; repeat:string };

export const brewListCopy: Record<Locale, BrewListCopy> = {
  en:{kicker:"Recipe archive",title:"Brew log",intro:"Revisit proven recipes and see how each controlled change affected the cup.",record:"Record brew",summary:"Brew summary",total:"Total records",average:"Average",highest:"Highest",method:"Method",allMethods:"All methods",minScore:"Minimum score",allScores:"All scores",andAbove:"and above",apply:"Apply",clear:"Clear",records:"records",page:"page",empty:"No records match these filters.",emptyHint:"Clear the filters or add a new brew.",ratio:"Ratio",temperature:"Temperature",duration:"Duration",bean:"Coffee",recipe:"Recipe",score:"Score",date:"Date",action:"Action",repeat:"Repeat brew"},
  tr:{kicker:"Reçete arşivi",title:"Demleme günlüğü",intro:"Kanıtlanmış reçetelere dön ve her kontrollü değişikliğin fincanı nasıl etkilediğini gör.",record:"Demleme kaydet",summary:"Demleme özeti",total:"Toplam kayıt",average:"Ortalama",highest:"En yüksek",method:"Yöntem",allMethods:"Tüm yöntemler",minScore:"Minimum puan",allScores:"Tüm puanlar",andAbove:"ve üzeri",apply:"Uygula",clear:"Temizle",records:"kayıt",page:"sayfa",empty:"Bu filtrelerle eşleşen kayıt yok.",emptyHint:"Filtreleri temizle veya yeni demleme ekle.",ratio:"Oran",temperature:"Sıcaklık",duration:"Süre",bean:"Çekirdek",recipe:"Reçete",score:"Puan",date:"Tarih",action:"Aksiyon",repeat:"Tekrar demle"},
  es:{kicker:"Archivo de recetas",title:"Registro de preparaciones",intro:"Recupera recetas probadas y comprueba cómo afectó cada cambio controlado a la taza.",record:"Registrar preparación",summary:"Resumen de preparaciones",total:"Registros totales",average:"Promedio",highest:"Máxima",method:"Método",allMethods:"Todos los métodos",minScore:"Puntuación mínima",allScores:"Todas las puntuaciones",andAbove:"o más",apply:"Aplicar",clear:"Limpiar",records:"registros",page:"página",empty:"Ningún registro coincide con estos filtros.",emptyHint:"Limpia los filtros o añade una nueva preparación.",ratio:"Proporción",temperature:"Temperatura",duration:"Duración",bean:"Café",recipe:"Receta",score:"Puntuación",date:"Fecha",action:"Acción",repeat:"Repetir preparación"},
  de:{kicker:"Rezeptarchiv",title:"Brühprotokoll",intro:"Bewährte Rezepte erneut ansehen und die Wirkung jeder kontrollierten Änderung prüfen.",record:"Brühung erfassen",summary:"Brühübersicht",total:"Einträge gesamt",average:"Durchschnitt",highest:"Höchste",method:"Methode",allMethods:"Alle Methoden",minScore:"Mindestwertung",allScores:"Alle Wertungen",andAbove:"und höher",apply:"Anwenden",clear:"Löschen",records:"Einträge",page:"Seite",empty:"Keine Einträge entsprechen diesen Filtern.",emptyHint:"Filter löschen oder eine neue Brühung hinzufügen.",ratio:"Verhältnis",temperature:"Temperatur",duration:"Dauer",bean:"Kaffee",recipe:"Rezept",score:"Wertung",date:"Datum",action:"Aktion",repeat:"Brühung wiederholen"},
  no:{kicker:"Oppskriftsarkiv",title:"Bryggelogg",intro:"Gå tilbake til velprøvde oppskrifter og se hvordan hver kontrollert endring påvirket koppen.",record:"Registrer brygg",summary:"Bryggoversikt",total:"Totalt antall",average:"Gjennomsnitt",highest:"Høyeste",method:"Metode",allMethods:"Alle metoder",minScore:"Minimumspoeng",allScores:"Alle poeng",andAbove:"og høyere",apply:"Bruk",clear:"Nullstill",records:"oppføringer",page:"side",empty:"Ingen oppføringer samsvarer med filtrene.",emptyHint:"Nullstill filtrene eller legg til et nytt brygg.",ratio:"Forhold",temperature:"Temperatur",duration:"Varighet",bean:"Kaffe",recipe:"Oppskrift",score:"Poeng",date:"Dato",action:"Handling",repeat:"Gjenta brygg"},
  ja:{kicker:"レシピアーカイブ",title:"抽出記録",intro:"実績のあるレシピを振り返り、管理された変更が味に与えた影響を確認します。",record:"抽出を記録",summary:"抽出の概要",total:"総記録数",average:"平均",highest:"最高",method:"方法",allMethods:"すべての方法",minScore:"最低スコア",allScores:"すべてのスコア",andAbove:"以上",apply:"適用",clear:"クリア",records:"件",page:"ページ",empty:"フィルターに一致する記録はありません。",emptyHint:"フィルターを解除するか、新しい抽出を追加してください。",ratio:"比率",temperature:"温度",duration:"時間",bean:"コーヒー",recipe:"レシピ",score:"スコア",date:"日付",action:"操作",repeat:"再抽出"},
  ko:{kicker:"레시피 보관함",title:"추출 기록",intro:"검증된 레시피를 다시 보고 통제된 변경이 맛에 미친 영향을 확인하세요.",record:"추출 기록",summary:"추출 요약",total:"전체 기록",average:"평균",highest:"최고",method:"방식",allMethods:"모든 방식",minScore:"최소 점수",allScores:"모든 점수",andAbove:"이상",apply:"적용",clear:"초기화",records:"개 기록",page:"페이지",empty:"필터와 일치하는 기록이 없습니다.",emptyHint:"필터를 초기화하거나 새 추출을 추가하세요.",ratio:"비율",temperature:"온도",duration:"시간",bean:"원두",recipe:"레시피",score:"점수",date:"날짜",action:"작업",repeat:"다시 추출"}
};
